#!/usr/bin/python3

import os

from mido import MidiFile

cv1 = MidiFile('brinstar.mid', clip=True)
cv3 = MidiFile('VampireKillerCV3.mid', clip=True)

print(cv1.tracks)
# del cv1.tracks[4]
# del cv1.tracks[4]

# cv1.tracks.append(cv3.tracks[4])
# cv1.tracks.append(cv3.tracks[5])

# cv1.save('mashup.mid')
